name: freighttool
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9.1
  - pyqt>=5.12.3
  - openpyxl>=3.0.6
  - pandas>=1.2.2
  - geopandas>=0.8.2
  - markdown>=3.3.4
  - jinja2>=2.11
  - packaging>=20.0
  - pyyaml>=5.4
