# LGVInputPaths config written on 2023-11-24 at 09:28
household_paths:
  name: LGV Households
  path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\1.Household Projections\UK_HH_projections_2018-MSOA.csv
  zc_path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\0.Lookups\MSOA model run Lookups\NTEM_MSOA_spatial.csv
bres_path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\2.BRES Data\BRES_2018_sections_GB_LSOA.csv
warehouse_path: U:\Lot3_LFT\2.LGV Model\VOA Data Replacement\ABP Data\20230525 ABP
  Warehouse Data\warehouses\warehouses_2018-floorspace_lsoa.csv
commute_warehouse_paths:
  medium: U:\Lot3_LFT\2.LGV Model\VOA Data Replacement\ABP Data\20230525 ABP Warehouse
    Data\commute_warehouses_medium\commute_warehouses_medium_2018-floorspace_lsoa.csv
  low: U:\Lot3_LFT\2.LGV Model\VOA Data Replacement\ABP Data\20230525 ABP Warehouse
    Data\commute_warehouses_low\commute_warehouses_low_2018-floorspace_lsoa.csv
  high: U:\Lot3_LFT\2.LGV Model\VOA Data Replacement\ABP Data\20230525 ABP Warehouse
    Data\commute_warehouses_high\commute_warehouses_high_2018-floorspace_lsoa.csv
parameters_path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\4.LGV_Parameters&Distributions\Newest TLDs and trip distribution\MSOA_input_tables.xlsx
qs606ew_path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\5.Occupation Data\QS606EW.csv
qs606sc_path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\5.Occupation Data\QS606UK.csv
sc_w_dwellings_path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\6.Dwellings Data\scotland_wales_dwellings.csv
e_dwellings_path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\6.Dwellings Data\Live_Table_123.xlsx
ndr_floorspace_path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs Base\7.Business Floorspace\NDR_business_floorspace.csv
lsoa_lookup_path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\0.Lookups\MSOA model run
  Lookups\LSOA_NTEM(MSOA_WITH_SCOTLAND)_spatial.csv
msoa_lookup_path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\0.Lookups\MSOA model run
  Lookups\NTEM_MSOA_spatial.csv
lad_lookup_path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\0.Lookups\MSOA model run
  Lookups\LAD_NTEM_spatial_missing_zones_added.csv
model_study_area: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\0.Lookups\MSOA model run
  Lookups\MSOA_Model_Study_Area.csv
cost_matrix_path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\8.Cost Matrix\MSOA_Distance_up_to_tertiary_roads_infilled.csv
trip_distributions_path: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\4.LGV_Parameters&Distributions\Newest TLDs and trip distribution\LGV_trip_distributions.xlsx
output_folder: E:\test
normits_pa_folder: I:\NorMITs Demand\Distribution Model\iter9.10.5\car_and_passenger\Final Outputs\Full PA Matrices
normits_to_msoa_lookup: U:\Lot3_LFT\2.LGV Model\LGV Model Inputs\0.Lookups\MSOA model run Lookups\noham_to_ntem_spatial.csv
normits_to_personal_factor: 0.04

